### ISSUE TITLE
Can't see icons

### ISSUE THREAD

**Issue by khromalabs** [trizen/menutray#1]
Hi thank you for this great application, fits perfectly in a WM like i3, I've installed in Ubuntu 14.04.02 and the app is showing in tray, just a minor issue, I can't see the icons. I tried gtk2 and gtk3, menu shows but no icons in both of them.

**Comment by trizen** [comment]
Make sure to execute `menutray -i` to generate a menu with icons and also make sure that a complete icon theme (like Faenza) is installed in `/usr/share/icons` and also the `/usr/share/pixmaps` directory exists too.

If there is a problem with the configuration file, execute `menutray -r` to regenerate it and try again. If the problem still persists, please let me know and we'll investigate even further.

**Comment by khromalabs** [comment]
Woha thank you for your lightning-fast answer. I'm executing this line:
`menutray -i -gtk3`

My ~/.config/gtk-3.0/settings.ini has a default Ubuntu icon theme:
`gtk-icon-theme-name=Humanity-Dark`
also this:
`gtk-toolbar-icon-size=GTK_ICON_SIZE_LARGE_TOOLBAR`

Also my .gtkrc-2.0 shows this line:
`gtk-icon-theme-name="Humanity-Dark"`

Directories `/usr/share/icons/Humanity-Dark` and `/usr/share/pixmaps` confirmed, permissions ok in both of them.

Thank you for your support!

PD. Already tried the regeneration, no luck.

**Comment by trizen** [comment]
Most probably, the menu icons are disabled in the GTK configuration files.

Try to add the the following line in `~/.config/gtk-3.0/settings.ini` and `~/.gtkrc-2.0`:
`gtk-menu-images=1`

**Comment by khromalabs** [comment]
Yes, you are right. Now I can see them. Thank you very much!

**Comment by trizen** [comment]
No problem.
