### ISSUE TITLE
"popup at cursor" does not work well in multi-monitor setups

### ISSUE THREAD

**Issue by xyxyxoxo** [trizen/menutray#11]
The "popup at cursor" option looks very promising and I recently pulled the latest git version because of it. 

It seems to work well in single-monitor setups, but, unfortunately, fails in my multi-monitor configuration in several ways.

Here's a visual of what my screen layout looks like:
![image](https://user-images.githubusercontent.com/30468319/51088341-7e57c200-176f-11e9-8e06-e45c4df8a25f.png)

eDPI is a laptop display (1366x768) and HDMI1 is an external monitor (1920x1080)

Some more context:
1. I've set up Openbox to bring up menutray when I left-click the desktop
2. The red dot signifies the bottom area of the external monitor where I click to trigger the first problem (see below)
3. I'm running tint2, which shows a panel on both monitors, but only the one on the laptop display has a notification area with menutray in it (you can only have one notification area/systray)

Problems:
1. When I click in the lower area of the second monitor (which, as you can see, is taller than the laptop display), the menu is not shown at all. With some crude debugging, I managed to log this error:

`Gtk-WARNING **: gtk_widget_size_allocate(): attempt to allocate widget with width 148 and height -23 at ~/.config/menutray/menu.pl line 73`

Looks like GTK is getting a negative height, which it can't handle?

2. Another problem (probably related to the first) is that clicks on the external monitor bring up the menu on the laptop display (the one with tint2 and its notification area). It looks like the mouse coordinates from the bigger external monitor are being applied to the smaller laptop display. And since the laptop display has a smaller height, it can lead to the first problem above when clicking in the red dot zone.

Is it possible to detect the monitor under cursor and pop up the menu on it? PyGtk has a method for this purpose (https://developer.gnome.org/pygtk/stable/class-gdkscreen.html#method-gdkscreen--get-monitor-at-point), do you think this can this be done in perl-gtk? Perhaps http://gtk2-perl.sourceforge.net/doc/pod/Gtk2/Gdk/Screen.html is relevant?

**Comment by trizen** [comment]
Thanks for reporting. Can you please check commit https://github.com/trizen/menutray/commit/fbdffe80bc545aba5e6e74100b9c13e340bb600e to see if it really fixes the issue. I don't have two monitors, so I cannot check myself. Thanks!

**Comment by xyxyxoxo** [comment]
Thanks for a quick response! The commit does fix the issue :)

**Comment by trizen** [comment]
Nice! Easy fix. :) Thanks for testing.
