### ISSUE TITLE
Encode.pm warning

### ISSUE THREAD

**Issue by xyxyxoxo** [trizen/menutray#12]
I've noticed that the latest git version prints this warning at startup:

```
Use of uninitialized value in subroutine entry at /usr/lib/x86_64-linux-gnu/perl/5.24/Encode.pm line 231.
Use of uninitialized value in subroutine entry at /usr/lib/x86_64-linux-gnu/perl/5.24/Encode.pm line 231.
```

The offending line in Encode.pm looks like this:
![image](https://user-images.githubusercontent.com/30468319/51088761-d93fe800-1774-11e9-94f4-fd42738d1d88.png)

This is happening on Debian Stretch. Perl lib that contains Encode.pm is libperl5.24:amd64, version 5.24.1-3+deb9u5.

**Comment by trizen** [comment]
Thanks! Fixed in the above commit.

**Comment by xyxyxoxo** [comment]
Awesome, thanks for the fix!
