### ISSUE TITLE
mangling escaped double-quotes in *.desktop file commands

### ISSUE THREAD

**Issue by xyxyxoxo** [trizen/menutray#14]
I think there may be a regression in the latest git version.

In desktop files, lines like `Exec=xterm -e "qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda ~/Documents/android.img; echo \"Press ENTER to exit.\"; read"` do not work any more, as all the double quotes are escaped only once in the resulting menu.pl, and the original slashes are stripped out.

As a result, when clicking the menu item, the shell tries to execute `xterm -e "qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda ~/Documents/android.img; echo "Press ENTER to exit."; read"`, which results in an error due to now unescaped double quotes.

I'm certain this didn't happen before. If necessary, I can revert to an older version of menutray and try and narrow down the problem to a specific commit, just let me know.

**Comment by trizen** [comment]
I think I know where the issue is. Working on it. Thanks for reporting.

**Comment by trizen** [comment]
Actually,  not a bug. The standard says that `\\` must be used for a literal backslah.

> The escape sequences \s, \n, \t, \r, and \\\\ are supported for values of type string and localestring, meaning ASCII space, newline, tab, carriage return, and backslash, respectively.

See: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#value-types

In this case, changing the line to:

```
Exec=xterm -e "qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda ~/Documents/android.img; echo \\"Press ENTER to exit.\\"; read"
```

works as expected.

**Comment by xyxyxoxo** [comment]
Interesting... 

Yes, if I use `\\`, the entry works in menutray and also when double-clicking the desktop file in, say, pcmanfm. But the dektop file does not validate anymore:

`error: value "xterm -e "qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda ~/Documents/android.img; echo \\"Press ENTER to exit.\\"; read"" for key "Exec" in group "Desktop Entry" contains a quote which is not closed
`

I used the official `desktop-file-validate` utility for validation. 

Anyway, I think you are right about the standard, so maybe the Debian Stretch utility is too old, I don't know. Not a big issue, as I can simply use single quotes to make it work with menutray and also pass validation.

**Comment by trizen** [comment]
It seems to need heavy escaping to make `desktop-file-validate` happy:

```
Exec=xterm -e \"qemu-system-x86_64 -m 2048 -boot d -enable-kvm -smp 3 -net nic -net user -hda \~/Documents/android.img\; echo \\\"Press ENTER to exit.\\\"\; read\"
```

**Comment by xyxyxoxo** [comment]
Thanks for the tip!
