### ISSUE TITLE
"Unmatched right curly bracket at menu.pl line 641"

### ISSUE THREAD

**Issue by taerath** [trizen/menutray#2]
Hi,

Menutray seems to be exactly the complement for i3wm that I was looking for (https://faq.i3wm.org/question/5413/program-to-browse-freedesktop-menu/), but unfortunately I can't get it to run.

I cloned the github repository and tried to run `./menutray.py`. I then ran it several times, each time installing an additional dependency (it would be really nice if all the dependencies were listed in e.g. the README file). After having installed all the dependencies, it failed with

```
./menutray: schema file `/home/nikratio/.config/menutray/schema.pl' does not exists!
```

I then made an educated guess and copied schema.pl from the repository into the above directory (though I have no idea why this is necessary and what that does). That seems to have helped, now
I just got the usage message -- but none of the options look like they would actually show the menu.

I wildly tried to run with `-g`, which gave me

```
$ ./menutray -g
Unmatched right curly bracket at /home/nikratio/.config/menutray/menu.pl line 641, at end of line
syntax error at /home/nikratio/.config/menutray/menu.pl line 641, near "}"
syntax error at /home/nikratio/.config/menutray/menu.pl line 828, near "}"
syntax error at /home/nikratio/.config/menutray/menu.pl line 932, near "}"
syntax error at /home/nikratio/.config/menutray/menu.pl line 958, near "}"
Unmatched right curly bracket at /home/nikratio/.config/menutray/menu.pl line 975, at end of line
syntax error at /home/nikratio/.config/menutray/menu.pl line 975, near "}"
```

Any help would be appreciated.

**Comment by trizen** [comment]
Hi,

It looks like menutray failed to generate a syntactically correct menu file, but I can't know why, unless I analyze the menu.pl file. If you can upload it somewhere, would be helpful. Thanks

**Comment by taerath** [comment]
Here you go: https://trialphaenergy.box.com/shared/static/ln6xp7uunz6tvefc3ny8733bdgo50p3h.pl
So calling it with `-g` is the correct thing to do? Should that bring up the menu?

Thanks for the quick response!

**Comment by trizen** [comment]
This problem seems to be caused by some .desktop files that doesn't provide a `Name` field. (fixed here: https://github.com/trizen/menutray/commit/09385ff2276de36c31178d08e6182ff7fa894619). Thank you very much for reporting this.

Edit: an installation guide has also been added here: https://github.com/trizen/menutray/blob/master/INSTALL.md
