### ISSUE TITLE
Feature Request: Hotkey

### ISSUE THREAD

**Issue by lasers** [trizen/menutray#3]
Nearly all XFCE plugins (for the panel) have a pointer feature (-p --pointer) that allows people to bindsym a shortcut that can bring up the said plugin on the mouse cursor.

Clipit (the clipboard manager) have hotkeys that allows people to utilize hotkeys that can bring up history, actions, menu, et cetera... on the mouse cursor.

I would like to request a feature that allows people to pop out a menutray on the mouse cursor with a hotkey just like clipit, dmenu, and others.  Hovering around to find the tray is annoying especially when you have multiple monitors. I want to use a shortcut that will simply bring it on the mouse cursor and the other benefit would be not having to leave my focused window (aka having the app opening by the focused window).

**Comment by trizen** [comment]
Excellent feature request. I would like to see this implemented as well.

**Comment by chxzqw** [comment]
+1.

I would like to do a bindsym to open the menu without using mouse.

**Comment by xyxyxoxo** [comment]
@chxzqw This is already possible by sending a USR1 signal to the menutray process, see https://github.com/trizen/menutray/pull/8. You can bind a key to smth like `sh -c "pkill -u $(whoami) -f menutray -SIGUSR1" ` to pop up the menu.

**Comment by trizen** [comment]
The `popup_at_cursor` config-option is now available in menutray v0.52. (disabled by default)

When this option is enabled, in combination with the command posted by Andrei, the menu will popup at the current position of the mouse cursor.
