### ISSUE TITLE
/usr/local/bin/hotshots does not exist

### ISSUE THREAD

**Issue by zenny** [trizen/menutray#4]
The following explains all:

>$ ./menutray -i
>Failed to open file '/usr/local/bin/hotshots': No such file or directory at /home/zenny/.config/menutray/menu.pl line 158.

Where on earth is this menu.pl file? Didn't see any in this repo! Or did I miss something?!

Thanks!

**Comment by trizen** [comment]
`menu.pl` is a Perl file generated automatically by menutray that represents the actual menu, based on the data found in `schema.pl`.

Regarding the error, please attach here the `schema.pl` and `menu.pl` files and I will start investigating the problem.

Thanks.

**Comment by trizen** [comment]
I don't know how to interpret your non-response, so I will close this issue. Please feel free to reopen it if the problem still persists and you're willing to collaborate on solving it. Thanks for understanding.
