### ISSUE TITLE
Multiple sub-categories under one category

### ISSUE THREAD

**Issue by radvansky** [trizen/menutray#6]
Hello,

Is it possible to read multiple categories from a desktop file and add them all to a single menu entry?

**Example:**

_Desktop Files read:_
[Desktop Entry A]
Categories=painting;

[Desktop Entry B]
Categories=drawing;

_schema.pl would do something like this:_
{cat => ['painting' and/or 'drawing', 'Image Applications', 'icon']}

_So that both desktop entries would appear under the single menu entry Image Applications._

**Comment by trizen** [comment]
Hi. Currently, this is not possible, but I'm considering adding support for this sometime in the future.

**Comment by radvansky** [comment]
Thank you for your quick reply! It's great to hear that, as I believe it would be a very useful feature for menutray the possibility to create menu entries 'grouping' multiple categories. 
Also, the tree option currently just accepts the 'item' type, creating  a 1 level menu. Possibly, another great feature would be the implementation of nested menus and submenus, accepting the 'category' type as well. 
Kind regards and, once again, thanks!

**Comment by trizen** [comment]
Starting with version 0.21 of `perl-linux-desktopfiles` ([Linux::DesktopFiles](https://metacpan.org/release/Linux-DesktopFiles)), we can merge multiple categories into a single one.

For example, in combining the "Network" and "AudioVideo" categories into a single category, named "network_and_multimedia", we add the following substitution inside the `config.pl` file:
```perl
{key => 'Categories', re => qr/(Network|AudioVideo)/, value => 'network_and_multimedia'},
```

while in the `schema.pl` we add the new category:
```perl
{cat => ['network_and_multimedia', 'Network & Multimedia', 'applications-multimedia']},
```

For a working example, see the attached file: [example.zip](https://github.com/trizen/menutray/files/1324687/example.zip)
